# Drift V2 pnpm workspace configuration
# Defines the packages that are part of the monorepo

packages:
  # Core packages
  - "packages/core"
  - "packages/detectors"
  - "packages/lsp"
  - "packages/cli"
  - "packages/ai"
  - "packages/vscode"
  - "packages/dashboard"
  - "packages/mcp"
  - "packages/galaxy"
  
  # Benchmark
  - "packages/cibench"
